name: Nightly

on:
  schedule:
    - cron: '0 15 * * *'

env:
  URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}

jobs:
  build-hook:
    runs-on: ubuntu-latest

    steps:
      - name: Hook build
        run: |
          curl -X POST -d {} $URL
